project_id = "ybdvhqmjlztlvrfurkaf"

[functions.openai-chat-stream]
verify_jwt = false

[functions.create-voice-agent]
verify_jwt = true

[functions.create-conversation]
verify_jwt = true

[functions.elevenlabs-text-to-speech]
verify_jwt = true

[functions.generate-embeddings]
verify_jwt = true

[functions.openai-conversation-assistant]
verify_jwt = true

[functions.openai-realtime-voice]
verify_jwt = true

[functions.openai-speech-to-text]
verify_jwt = true

[functions.openai-text-to-speech]
verify_jwt = true

[functions.openai-voice-chat]
verify_jwt = true

[functions.semantic-search]
verify_jwt = true

[functions.voice-analytics]
verify_jwt = true

[functions.manage-voice-agents]
verify_jwt = true

[functions.tts-worker]
verify_jwt = false